dist: trusty
sudo: false
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
      - cppcheck
env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release
script:
  - cppcheck -I driver/ --enable=all --inconclusive --platform=unix64 --std=c89 --error-exitcode=2 -f driver/
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-6
  - export CXX=/usr/bin/g++-6
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  # Run your build commands next
  - cmake . -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
  - make VERBOSE=1
  - sudo ./run_test
