dist: trusty
sudo: required
language: c
before_install:
  - sudo apt update -yq
install:
  - sudo apt install -yq cppcheck
script:
  - cppcheck -I driver/ --enable=warning --enable=style --enable=performance --enable=portability --enable=information --enable=missingInclude --inconclusive --platform=unix64 --std=c89 --error-exitcode=2 -f driver/
  - make
  - sudo ./bin/run_test
