dist: trusty
before_install:
  - sudo apt update -yq
install:
  - sudo apt install cmake cppcheck
env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release
script:
  - cppcheck -I driver/ --enable=all --inconclusive --platform=unix64 --std=c89 --error-exitcode=2 -f driver/
  - cmake . -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
  - make VERBOSE=1
  - sudo ./run_test
